PACKAGE_NAME="mygica-a681"
PACKAGE_VERSION="0.1.0"
BUILT_MODULE_NAME[0]="mygica_a681"
DEST_MODULE_LOCATION[0]="/updates/dkms"
AUTOINSTALL="yes"
MAKE[0]="make KERNELRELEASE=${kernelver}"
CLEAN="make KERNELRELEASE=${kernelver} clean"
